### ISSUE TITLE
Emit warning if no dist is available

### ISSUE THREAD

**Issue by andersevenrud** [os-js/osjs-server#11]
This came up during a conversation on Gitter.

It would probably be useful if the server could check the `dist/` directory, and if it was not satisfied a message would appear with some suggestions of what might have gone wrong:

* Forgot to run `npm run buld` ?
* Did an error occur while running `npm run buld` ?

**Comment by SpaceboyRoss01** [comment]
So like a log file that the server checks to see if `dist` was correctly created?

**Comment by andersevenrud** [comment]
Just print to stderr if `index.html` or the pattern `osjs.*` was not found inside `dist/` .

**Comment by SpaceboyRoss01** [comment]
Ah
