### ISSUE TITLE
Add 'routeAuthenticated' group resolution options

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/osjs-server#13]
**Edited**

Currently `routeAuthenticated` matches groups with `.every()`, not `.some()`.

Both behaviours should be supported.

**Comment by andersevenrud** [comment]
Modified title and description.

It's generally a good idea top copy/paste conversations from Gitter when doing stuff like this.

Saves me a lot of work :)

**Comment by SpaceboyRoss01** [comment]
Didn't really know what to call it.

**Comment by andersevenrud** [comment]
Note-to-self: A solution for supporting both would be:

```
routeAuthenticated(string, callback, options);
```

Where `options` can be either an `Array` using default behavior or: `{every: true, groups: []}`.
