### ISSUE TITLE
Add ranged HTTP response support

### ISSUE THREAD

**Issue by andersevenrud** [os-js/osjs-server#15]
I'm pretty sure that I actually added this, but maybe it was left in a separate branch I forgot to merge :thinking:

**Comment by andersevenrud** [comment]
@fallenczar reported an issue with seeking media on Gitter.

**Comment by andersevenrud** [comment]
@fallenczar This should now work if you run `npm update @osjs/server`

**Comment by fallenczar** [comment]
works flawlessly!
