### ISSUE TITLE
When downloading files, the name on the client is always "readfile"

### ISSUE THREAD

**Issue by valp124** [os-js/osjs-server#18]
Downloading any file from the File Manager results in a local file called "readfile."
(I tried testing this from the official demo site, to make sure it's not only our instance that does that, but there I get "File not found" for all files.) As per @andersevenrud, it's because the server does not send back a spesific header to let the browser know the filename. It takes readfile which is the last part of the URL path.

**Comment by andersevenrud** [comment]
I'll look into this ASAP :) Thanks for reporting!

**Comment by andersevenrud** [comment]
Run `npm update @osjs/server` and restart your server process, and this issue should now be resolved.

**Comment by andersevenrud** [comment]
As for the demo server, I'm not sure what's going on there. I'll look at that later.

**Comment by valp124** [comment]
Awesome, thank you so much!
