### ISSUE TITLE
User group checking is too strict

### ISSUE THREAD

**Issue by josephjeno** [os-js/osjs-server#22]
Currently if an application (or mountpoint) has multiple groups, ie ["admin", "webce"], the user must be a member of both groups in order for the application to be permissioned.  I think the application should be permissioned if a user is a member of any one of the application groups.

**Comment by andersevenrud** [comment]
PR incoming: https://github.com/os-js/osjs-server/pull/23

I'll add this functionality on the client before merging and releasing :)

**Comment by andersevenrud** [comment]
3.0.47 has now been released with these changes.

The following settings should resolve your issue:
```
{
  attributes: {
    strictGroups: false
  }
}
```

**Comment by andersevenrud** [comment]
Since you reported it works fine on the Gitter chat I'll be closing this one. Thanks!
