### ISSUE TITLE
How download a file when we have its content instead of the path.

### ISSUE THREAD

**Issue by miladhashemi** [os-js/osjs-server#33]
In openstack I have an operation that returns object content for me.
for example if object be a *.html file, returns "<html>....</html>" to me.

I use this api in my server adapter and it returns object's content properly.

### My API calling in adapter
```javascript
const path = require('path')
const {Readable} = require('stream')

//Openstack API
const Monster = require('./src/Monster')

////check if path is at mountpoint(root)
const checkMountPoint = dir => dir.split(':/').splice(1).join(':/')


///get container name
const containerName = dir => dir.split('/').splice(1, 1)[0]

///get object name
const objectName = dir => path.basename(dir)

const readfile = (path, options, mon) => {
    /*
    * getObjectContent(container, object) returns object's content.
    * example1: png file returns @PNG....
    * example2: html file returns <html>....
    * */
    if (!options.hasOwnProperty('download')) {
        return mon.getObjectContent(containerName(path), objectName(path)).then(result => {
            if (result.status === 200) {
                const readable = Readable.from(result.message)
                return readable.on('end', chunk => chunk)
            } else {
                return `Error: ${result.status}`
            }
        });
    } else if (options.download) {
        return mon.getObjectContent(containerName(monster), objectName(monster)).then(result => result.message)
    }
}

module.exports = (core) => {
    const monster = new Monster("http://localhost:12345/auth/v1.0")
    monster.login('test:tester', 'testing')

    return {
        readfile: vfs => (path, options) => readfile(path, options, monster),
    }
};

```

### Output
But as i click on download in filemanager it show me:
‍‍‍‍‍‍‍```"TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received undefined"```

### Error Source
I think the source of this error is in server/src/vfs.js, where used result.path for getting basename(line 134)
```javascript
if (method === 'readfile' && options.download) {
    res.attachment(path.basename(path.basename(result.path)));
}
```
Is there a way to download an object after i get its content?

 **@osjs/server v3.1.3**

**Comment by andersevenrud** [comment]
I've released a new version of `@osjs/server` (3.1.4) that should take care of your issue :)

Thanks for reporting!

**Comment by miladhashemi** [comment]
> I've released a new version of `@osjs/server` (3.1.4) that should take care of your issue :)
> 
> Thanks for reporting!

Thanx.
I'm testing it as soon as possible.

**Comment by miladhashemi** [comment]
Finaly I tested it.
It works fine for text file, but I have problem for binary files like image,....
for example api returns `�PNG  IHDR0W�.....`

I use `XMLHttpRequest` for getting file's content.

And my adapter code for readfile is here:
```javascript
const readfile = (monster, options, mon) => {
    return mon.getObjectContent(containerName(monster), objectName(monster)).then(result => {
        if (result.status === 200) {
            let chunks = ''
            let readable = Readable.from(result.message)
            return readable.on('data', (chunk) => chunks += chunk).once('end', (chunks) => chunks)
        } else {
            return `Error: ${result.status}`
        }
    });
}
```

**Comment by andersevenrud** [comment]
It looks like you're converting (possibly) a Buffer, into a Readable, then into string. Why ? The VFS API is based on streams. Also, converting into plain text certainly messes up your binary.

If you're creating a HTTP request, you can just get a stream from there and just return directly.

Another thing I see is that you turn Exceptions into a text result as well. That will mess things up.

You can just do this if it's a promise:

```
const createHttpRequestAsStrem = () => createHttpRequest()
  .then(response => {
    if (response.status !== 200) {
     throw new Error('Request error')
    }
    return response.stream
  })

const readfile = (a, b, c) => createHttpRequestAsStream()
```

**Comment by miladhashemi** [comment]
Yes,
The problem was XMLHttpRequest in node. In all situation was returingn text file. 
I altered it with axios and now I can get file stream.

**Comment by andersevenrud** [comment]
Sweet!
