### ISSUE TITLE
Interacting with user home directory without VFS

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-server#41]
Hi,
Using proc service provider in following code, I can list the folders in osjs project root.
However I need to list the folders in the **home directory of logged in user** via PAM adapter.
How can I do that?
```js
function getFolderList(){
        osjs.make('osjs/proc')
       .pty('ls' , '-d */')
        .then(p => {
            p.on('data', data =>{     
               // do something
            })
            p.on('exit', code => console.info('EXITED', code))
            p.on('spawned', () => {}); // Spawn successful
            p.on('error', error => console.error(error)); // Spawn errors
            p.send('Hello World\n');
            p.kill();
          })
    }
```
below is my serve config, and I can see home directory of logged in user in file manager.

```
{
  vfs: {
    root: '/home'
  }
}
```

**Comment by andersevenrud** [comment]
NB: I transfered this issue to the `@osjs/server` repository and made the title a bit more generic so that it's easier for other people to find :)

**Comment by andersevenrud** [comment]
I'm closing this issue because there's been no response in a week. Feel free to re-open if you haven't gotten to the bottom of this. I'm just cleaning up open issues :)
