### ISSUE TITLE
Retrieving Session Data 

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-server#43]
Hi
In my server-side custom **Authentication adapter**, I have added some data to **session variable.**
How can I access to session data in my server-side custom **VFS adapter**?

**Comment by andersevenrud** [comment]
You can get the session from `req.session.user`.

**Comment by andersevenrud** [comment]
Come to think of it, the HTTP request is not passed down to the VFS adapter.

However the `options` object passed to all VFS adapter methods (usually the last argument) contains `session.user` that is coped from the HTTP requests :)

**Comment by mahsashadi** [comment]
Thanks a lot :)
Yes, since Http request was not available in VFS adapter, I need to ask it here.
Great, now it works by using options :+1:

**Comment by andersevenrud** [comment]
Great :ok_hand:
