### ISSUE TITLE
adding authentication adapter 

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-server#44]
Hi
I have added an authentication adapter to OSjs in server side.

Is it recommended to add more functions (than login, logout, init) to this adapter?
For example I need a `getProjects` function which returns project list of logedin user.

How can I access these functions in other files in server side or even client side?

**Comment by andersevenrud** [comment]
The authentication adapter is designed to only contain methods related to login and the HTTP routes are set up statically, meaning you cannot add anything here.

Create your own service provider instead:


```
class MyApiServiceProvider
{
  constructor(core, options = {}) {
    this.core = core;
    this.options = options;
  }

  provides() {
    return ['mahsashadi/users'];
  }

  async init() {
    const {routeAuthenticated} = this.core.make('osjs/express');

    routeAuthenticated('GET', '/mahsashadi/users', async (req, res) => {
      const projects = await this.getProjects(req.session.user)
      res.json(projects)
    });

    this.core.singleton('mahsashadi/users', () => ({
      getProjects: user => this.getProjects(user)
    }));
  }
}
```

Usage on client:

```
const projects = await core.request('/mahsashadi/users')
```

Usage on server:

```
const projects = await core.make('mahsashadi/users').getProjects({ id: 123 })
```

**Comment by andersevenrud** [comment]
I meant to write `mahsashadi/projects` not `mahsashadi/users`.... but you get the idea.
