### ISSUE TITLE
supporting utf-8 filename

### ISSUE THREAD

**Issue by miladhashemi** [os-js/osjs-server#49]
https://github.com/os-js/osjs-server/blob/4e00f3133fbf708c44725de64fc078283a944029/src/vfs.js#L185-L186

Hi,
These line of code causes utf-8 file encoding file doesn't work properly, It should alter with these lines of code.
```js
      const filename = encodeURIComponent(path.basename(args[0]));
      res.append('Content-Disposition', `attachment; filename*=utf-8''"${filename}"`);
```

**Comment by andersevenrud** [comment]
Thanks for the PR!

This has been released with `@osjs/server@3.1.18`
