### ISSUE TITLE
Return value of `writefile` in VFS?

### ISSUE THREAD

**Issue by MoradiDavijani** [os-js/osjs-server#51]
Hi,

We have an issue in developing a VFS adapter. The issue is we don't know what should be the return value of the `writefile` function.

In the "Methods" section on the [VFS tutorial](https://github.com/os-js/manual.os-js.org/tree/master/src/v3/tutorial/vfs), it says the return value of `writefile` is `boolean`. But, [this line](https://github.com/os-js/osjs-server/blob/master/src/vfs.js#L243) is forcing the `writefile` to return a numeric value. Am I missing something?

**Comment by andersevenrud** [comment]
Looks like a mistake in the VFS documentation. It should return the size of the written file.

Note that the return value is not really used anywhere.

**Comment by andersevenrud** [comment]
I pushed a fix for the documentation that will be auto-deployed ASAP :)
