### ISSUE TITLE
Users Issues

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-server#54]
Hi, I have two questions:

1. Since `vfs.call`  gets `user` parameter as below code line, how can I send the whole session data to my vfs adapter `option` object,
```js
// I need session object to be passed instead of only user object
 await vfs.call({method: 'stat', user: {username: userInfo.username}}, filePath)
```

2. How can I make some of the applications available to logged-in user. In other words, I need to set different subset of applications available for each user.

**Comment by andersevenrud** [comment]
> how can I send the whole session data to my vfs adapter 

You need to pass the session data from a request, i.e. `req.session.user`.

> How can I make some of the applications available to logged-in user. In other words, I need to set different subset of applications available for each user.

You want to control what application list based on a user ?

**Comment by mahsashadi** [comment]
> You need to pass the session data from a request, i.e. `req.session.user`.

Whould you please rewrite the vfs.call method above with this?

**Comment by andersevenrud** [comment]
> Whould you please rewrite the vfs.call method above with this?

I'm not sure what you're asking here. Do you mean the snippet in your first post ? If so I'll need a bit more context.

**Comment by mahsashadi** [comment]
```js

// I have session object in userSession parameter
async function myFunc({req, res, vfs, userSession }){
       // I need to pass userSession to my vfs adapter
        await vfs.call({ method: 'stat', session: userSession }, filePath).then(response => {
            res.json({
              //
            });
})
}
```


 some parts of my vfs adapter is as below:
```javascript
const before = async (vfs, options, core) => {
  let swift;
  // I need to have userSession in options.session
  if (options.session.x) {
    // ;
  } else if (options.session.y) {
    //
  }
  return Promise.resolve(swift);
};

module.exports = (core) => {
  return {
    stat: vfs => (monster, options) => before(vfs, options, core).then((swift) => stat(monster, swift)),
    //
  };
};
```

**Comment by mahsashadi** [comment]
> You want to control what application list based on a user ?

I did not understand your question.
To describe more, as an example, I need when user _test1_ logins, applications A and B become available in utilities, and when user _test2_ logins, application B and C appears.

**Comment by andersevenrud** [comment]
```javascript
async function myFunc({req, res, vfs, userSession }){
  await vfs.call({ method: 'stat', user: req.session.user }, filePath).then(response => {
    res.json({});
  })
}
```

> some parts of my vfs adapter is as below:

As you demonstrated here, you have session in `options`.

> To describe more, as an example, I need when user test1 logins, applications A and B become available in utilities, and when user test2 logins, application B and C appears.

You can hide (and disallow from running) this via groups, or using `blacklist` property in a custom auth adapter login response. This is an array of package names.

If you need your own behavior on this, you can override the `packages.manifest` configuration entry to point to a custom HTTP endpoint on the server that returns a list (you can get the list via packages service provider, or reading the manifest file from `dist/`) populated with what you need. Here you can do filtering via the `session` object etc.

**Comment by andersevenrud** [comment]
> You can hide (and disallow from running) this via groups

Some docs on this here:

https://manual.os-js.org/guide/disabling-packages/

**Comment by mahsashadi** [comment]
> ```js
> async function myFunc({req, res, vfs }){
>   await vfs.call({ method: 'stat', user: req.session.user }, filePath).then(response => {
>     res.json({});
>   })
> }
> ```

this request is not an internal request, so it does not contain session that I need, I previously store the whole session object in parameter `userSession`, and I need the whole session object (I added some other key values to it), not only the value of `user` key.

**Comment by andersevenrud** [comment]
I'm curious, what are these "internal requests" for ?

**Comment by mahsashadi** [comment]
It is for office application that I have recently contributed.
https://github.com/BurnaSmartLab/osjs-office-collabora/blob/master/wopi.js  (line 88)
I need to change this vfs call to send the whole session object.

**Comment by andersevenrud** [comment]
I'm not sure I understand this. You have an endpoint there that is attached to the OS.js server, so you would have access to the `req.session.user`. Is the problem that these endpoints are called from an external service that does not have the OS.js cookie ?

**Comment by andersevenrud** [comment]
btw, you have to remove this line: https://github.com/BurnaSmartLab/osjs-office-collabora/blob/4f7ebb7a89ff870f5d8c84835918fff33cc91fde/server.js#L9 it will interfere with the internal parsing!

**Comment by andersevenrud** [comment]
> Is the problem that these endpoints are called from an external service that does not have the OS.js cookie ?

Looking at the collabra docs, it seems that this is probably the case. And if it is, then your current method of doing this will not work in a multi-user environment. I'll have a look at the docs and see if there's a way to do this via tokens.

**Comment by andersevenrud** [comment]
If you actually have `req.session.user` from OS.js at this point: https://github.com/BurnaSmartLab/osjs-office-collabora/blob/master/wopi.js#L56

Then you can do the following to create a working prototype:

1. Instead of `test` do a  `JSON.stringify({ user: req.session.user })`
2. It looks like you have encrypt/descrypt here in your codebase... use that to obfuscate the token
3. Then you can `const { user } = JSON.parse(decrypt(req.query.access_token))` and use that in your VFS calls

Notice that I wrote **prototype** there.... the best way to solve this is to have a database running alongside your solution so that you:

1. Have a database table with these fields: `token`, `data`, `expiresAt`
2. You create this token on demand in that discovery  thing and set the `token` to some random string, `data` as serialized JSON (same as above), and expiration with a sane time (like 12hours max)
3. On the endpoints that uses a token, you look it up in the database with `token = req.query.access_token`, then throw an exception if it was expired -- if not you can use `data` to what you need.

**Comment by andersevenrud** [comment]
The above comment only works if wopi discovery actually supports a token like you have there...which I can't seem to find out via their docs.

**Comment by mahsashadi** [comment]
sorry, I think we totally missunderstood the problem!

My exact requirement is to have the **whole session object** (not session.user) in my vfs-adapter by calling `vfs.call()` .... currently only session.user is available.

I examined the server code more carefully and I understood it is because of this [code line](https://github.com/os-js/osjs-server/blob/31d4e3a9545a303acfff335834c03c49fc969b66/src/filesystem.js#L212)

Indeed by changing `req.session = {user};` to `req.session = options.session;` my problem is totally fixed.

Can this code line be changed? If so, I can make a pull request to contribute on it.

**Comment by mahsashadi** [comment]
Sorry ! I think we totally missunderstood the problem.

My exact request is to send the **whole session object** (not only session.user) to `vfs.call()`.
 In current api, in [this code line](https://github.com/os-js/osjs-server/blob/31d4e3a9545a303acfff335834c03c49fc969b66/src/filesystem.js#L212), only `req.session.user` is set as `req.session`, not the whole ... so the rest of the session object is not passed through following requests and missed.

Indeed, for an example, if I could call vfs.call like below:
```js
vfs.call({method: 'readfile', 
          user: {username: req.session.user.username}, 
          session: req.session},
          filePath)
```

and change `req.session = {user}` of [this code line](https://github.com/os-js/osjs-server/blob/31d4e3a9545a303acfff335834c03c49fc969b66/src/filesystem.js#L212) to `req.session = {options.session}`, the problem is totally fixed.

**Comment by andersevenrud** [comment]
I'm not convinced that I totally misunderstood the problem, because this will **not** work properly: https://github.com/BurnaSmartLab/osjs-office-collabora/blob/master/server.js#L18

**Comment by andersevenrud** [comment]
> I'm not convinced that I totally misunderstood the problem, because this will not work properly

Just to expand on this. Creating a state on the server that stores the "last user" has no guarantee of working like you expect it to if there are more than one users logged in.

There are two scenarios that can happen here:

1. If for some reason the "discovery" endpoint is not called for example before "files"

**Comment by andersevenrud** [comment]
Ops... ignore the close and the message I deleted. I clicked the wrong button.... and I will rewrite the message.

**Comment by mahsashadi** [comment]
> I'm not convinced that I totally misunderstood the problem, because this will **not** work properly: https://github.com/BurnaSmartLab/osjs-office-collabora/blob/master/server.js#L18

Yes, in this way, I should replace it with `userInfo=req.session` 
You mean this?

**Comment by mahsashadi** [comment]
> I have at least published a new server version that allows you to specify the following:
> 
> ```
> await vfs.call({ method: 'stat', session: sessionData }, filePath)
> ```

Great, It will cause not losing the rest of the session data 👍

**Comment by andersevenrud** [comment]
> Yes, in this way, I should replace it with userInfo=req.session
> You mean this?

No, I mean you cannot do anything like that. Just think about it -- If you have two users: A and B, only A is using office. Now if user B calls the "wopi/files/:fileId" endpoint, your code will think that it's user A that's doing this.

That's just one scenario where this will fail -- there are others as well.

**Comment by mahsashadi** [comment]
Oh, I think now I get your point. You are right.
Because now I call  [discovery API](https://github.com/BurnaSmartLab/osjs-office-collabora/blob/1365adba409b02b79fc35e3d40f62f1496fd2c56/server.js#L14) whenever a file is aimed to open with office, I did not face this problem, But if I change it to call once I will have your mentioned problem.
Am I right?

**Comment by andersevenrud** [comment]
> Because now I call discovery API whenever a file is aimed to open with office, I did not face this problem, But if I change it to call once I will have your mentioned problem.

My point is that you cannot save the session in a variable like you're doing. That has zero guarantee to work.

You need to implement some kind of mechanic with the token system as I've mentioned so that you create a session in collabra.

**Comment by mahsashadi** [comment]
You are completely right, Thanks a lot for your useful comment. Since I need the whole session, I assign it to the token: https://github.com/BurnaSmartLab/osjs-office-collabora/blob/552cf4fd8475f3e0f3b5611df51d813eec37c15e/wopi.js#L54



> btw, you have to remove this line: https://github.com/BurnaSmartLab/osjs-office-collabora/blob/4f7ebb7a89ff870f5d8c84835918fff33cc91fde/server.js#L9 it will interfere with the internal parsing!

And for this comment, the [PutFile](https://wopi.readthedocs.io/projects/wopirest/en/latest/files/PutFile.html) API, which is responsible for save action, will not work by removing that line. The new content in the save action is sent in req.body.

**Comment by andersevenrud** [comment]
> And for this comment, the PutFile API, which is responsible for save action, will not work by removing that line. The new content in the save action is sent in req.body.

I've added so that you can configure this globally: https://github.com/os-js/osjs-server/commit/5de67700ea9aada5e2791831269470ae2044578c

Just as a reminder. **Never** set globals (or modify express) from an application like this. You have to do this via the bootstrap script (`src/server/index.js`) or a service provider.

> You are completely right, Thanks a lot for your useful comment. Since I need the whole session, I assign it to the token:

As I mentioned in a previous comment, you really should not set the actual session as the token... because that's not a token :sweat_smile: There should be a database in place where you can exchange tokens for a session.

**Comment by andersevenrud** [comment]
I'm closing this issue because it was solved. We can continue the discussion here though :)
