### ISSUE TITLE
Browser tabs issue

### ISSUE THREAD

**Issue by maryam4s26** [os-js/osjs-server#82]
Hello @andersevenrud .
Suppose a user logs in in a browser tab and the user's cookie is saved and reconnected to osjs in another tab, why all the login operations are done again.
This is also seen in refreshing the browser tab. When we refresh a tab without any logout operation, the login operation is performed again.

**Comment by andersevenrud** [comment]
You can enable the following setting to remember the cookie: https://github.com/os-js/osjs-client/blob/master/src/config.js#L155

More information: https://github.com/os-js/OS.js/issues/761
