### ISSUE TITLE
Mountpoint not found error

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-server#86]
Hi, 

When user is idle for some time, by clicking in file-manager mountpoint we faced the belowe error

(client image and server logs shown below, are for different sessions):

```
GET /icons/GnomeIcons/icons/applications-utilities.png 200 3464 - 3.941 ms
GET /icons/GnomeIcons/icons/applications-office.png 200 3438 - 5.998 ms
user is login out ...
POST /logout 200 2 - 6.910 ms
WebSocket connection closed
GET / 200 738 - 3.117 ms
GET /vendors~osjs.css 200 31520 - 11.115 ms
GET /osjs.css 200 1047 - 11.289 ms
GET /osjs.js 200 19492 - 9.479 ms
GET /vendors~osjs.js 200 511588 - 10.076 ms
GET /f4cfc6708cf6bfc17d4b1e775f594ae2.png 200 102543 - 3.643 ms
GET /ping 200 2 - 1.898 ms
GET /ping 200 2 - 2.942 ms
GET /apps/Textpad/icon.png 200 2460 - 11.670 ms
GET /apps/Preview/icon.png 200 1824 - 10.876 ms
GET /apps/Draw/icon.png 200 4214 - 9.940 ms
GET /apps/Calculator/icon.png 200 1391 - 13.162 ms
GET /apps/monster-sharing/assets/icon.png 200 21456 - 15.123 ms
GET /apps/HTMLViewer/icon.png 200 1935 - 15.746 ms
GET /apps/MusicPlayer/icon.png 200 3569 - 7.932 ms
GET /apps/Office/assets/appicon.png 200 64857 - 4.633 ms
Error: Mountpoint not found for 'cont_m_abolhabib1_abolhabib2'
    at createError (/usr/src/osjs/node_modules/@osjs/server/src/utils/vfs.js:150:13)
    at /usr/src/osjs/node_modules/@osjs/server/src/utils/vfs.js:164:11
    at /usr/src/osjs/node_modules/@osjs/server/src/vfs.js:148:23
    at /usr/src/osjs/node_modules/@osjs/server/src/vfs.js:82:43
    at Layer.handle [as handle_request] (/usr/src/osjs/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/osjs/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/src/osjs/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/src/osjs/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/osjs/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/usr/src/osjs/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/src/osjs/node_modules/express/lib/router/index.js:280:10)
    at /usr/src/osjs/node_modules/@osjs/server/src/vfs.js:107:7 {
  code: 403
}
GET /vfs/readdir?path=cont_m_abolhabib1_abolhabib2%3A%2F&options=%7B%22showHiddenFiles%22%3Afalse%7D 403 1113 - 5.251 ms
GET /sounds/FreedesktopSounds/bell.mp3 206 20826 - 6.120 ms
```
![Screenshot from 2024-01-06 18-33-30](https://github.com/os-js/osjs-server/assets/70196035/bf463f8b-95cd-49d5-9871-4d3689d2cc50)

Is this related to websocket connect which seems to be closed after some time?
How we can fix that?
@andersevenrud

**Comment by mahsashadi** [comment]
BTW, we have a server-mounting service-provider which does unmounting when logging-out event is raised.

Does this event raised by being idle?
```js
const {ServiceProvider} = require('@osjs/common');

class MountingServiceProvider extends ServiceProvider {

  constructor(core, options = {}) {
    super(core, options);
    this.core = core;
    this.options = options;
  }

  provides() {
    return [
      'monster/mount',
    ];
  }

  init() {
    this.core.singleton('monster/mount', () => ({
      mountContainers: (...args) => this.mountContainers(...args),
      unmountContainers: (...args) => this.unmountContainers(...args)
    }));
  }

  async start() {

    await this.core.on('osjs/core:logged-in', async (session) => {
      await this.mountContainers(session)
    });

    await this.core.on('osjs/core:logging-out', async (session) => {
       await this.unmountContainers(session);
    });
  }

  async mountContainers(session) {
    // const fs = this.core.make('osjs/fs');
    // const containers = session.user.containers;
    // const authType = session.user.authType;
    // const projectId = Object.keys(session.openstackAuth.projects)[0];
    // containers.forEach(element => {
    //     if(!this.isDuplicate(fs, element, projectId)) {
    //       fs.mount({
    //         name: element,
    //         id: projectId,
    //         adapter: 'monster',
    //         attributes: {}
    //       });
    //     }
    // });
  }

  async unmountContainers(session) {
    const authType = session.user.authType;
    const projectId = Object.keys(session.openstackAuth.projects)[0];
    this.unmount(projectId);
}


//   isDuplicate(fs, mountPointName, mountPointId) {
//     const duplicate = fs.mountpoints.find(item => item.id === mountPointId && item.name === mountPointName);
//     return duplicate ? true : false;
//   }

  async unmount(item) {
    this.core.make('osjs/fs').mountpoints = this.core.make('osjs/fs').mountpoints.filter(ele => ele.id !== item);
    this.core.config('vfs').mountpoints = this.core.config('vfs').mountpoints.filter(ele => ele.id !== item);
  }

  destroy() {
  }
}

module.exports = MountingServiceProvider;

```

**Comment by andersevenrud** [comment]
Are you logging out the user?

```
user is login out ...
POST /logout 200 2 - 6.910 ms
```

The first message is not from core.

**Comment by mahsashadi** [comment]
No I add a console.log like below, but it seems it happens even when I did not log-out from desktop. 
```
await this.core.on('osjs/core:logging-out', async (session) => {
       console.log('user is login out ...');
       await this.unmountContainers(session);
    });
```

**Comment by mahsashadi** [comment]
No I add a console.log like below, but it seems it happens even when I did not log-out from desktop. 
```
await this.core.on('osjs/core:logging-out', async (session) => {
       console.log('user is login out ...');
       await this.unmountContainers(session);
    });
```

**Comment by mahsashadi** [comment]
When the user is logging in the ws connection is opened, and it will be closed by logging out, Right?

If the problem is something related to ws, what else can close the connection?

**Comment by andersevenrud** [comment]
It says POST to logout. That means the client requested this. Are you sure there is not code another place?

**Comment by mahsashadi** [comment]
Maybe the above log is generated when the user logged out.

But we have the situation which the user is idle and server logs "mountpoint not found" after some times (by clicking on mount-point in the client-side), as below:
![ima_6de1abb](https://github.com/os-js/osjs-server/assets/70196035/5420b1b5-aeb8-48e1-9914-7ec88d9bd748)

**Comment by andersevenrud** [comment]
Is this reproducible with fresh and clean istall with default configs and mount?

**Comment by mahsashadi** [comment]
I faced it in my own vfs adapter, which has some service providers to work, So unfortunately no.

**Comment by andersevenrud** [comment]
Then I am not sure how to help 🫤. If you find a way to reproduce, share it and I will look.

**Comment by mahsashadi** [comment]
Thanks, for sure.

Just to have a hint, can be ralated to ws? I mean after some time being idle, the ws does not work.

**Comment by mahsashadi** [comment]
and Is there any other situation in which `osjs/core:logging-out` calls in client-side?

**Comment by andersevenrud** [comment]
WS should not be related. Session is HTTP. WS only sends messages (by default).

Any event related to login/logout explicitly comes from using auth api login/logout.

Do you use a reverse proxy?

**Comment by mahsashadi** [comment]
No I am not using reverse proxy in my local.

Does it make different?

**Comment by andersevenrud** [comment]
Apache can make WS drop out and not being able to connect. But if you don't have that as reverse-proxy then you're OK.

**Comment by mahsashadi** [comment]
I think our sessions are mixed up while logging out and then unmounting ( it does not unmount the expected ones) 

So is there any point in unmounting? Can we leave the mountpoints as they are and not unmount them by logging out? 

@andersevenrud

**Comment by andersevenrud** [comment]
> I think our sessions are mixed up while logging out and then unmounting ( it does not unmount the expected ones)

Aha. You can manage mountpoints around sessions wither usernames and/or unique ids. I see now (did not read it closely earlier) that in your service that it does not do this, so I can understand why you run into this.

> So is there any point in unmounting?

It all depends on the mountpoint (and the underlying connections etc.) and your needs, but in most cases it doesn't really matter it it's permanently mounted. So maybe not ?!

**Comment by maryam4s26** [comment]
The process is that the mountpoint is added while the user logged in, and we dont change it after that.

As you said, one thing that we can do is to add a session_id in mountpoints, for instanse:

![Screenshot from 2024-01-06 21-41-33](https://github.com/os-js/osjs-server/assets/65979871/4152307c-88fa-4ca9-a4b3-4362dd9b6680)


And the other option is do not unmounting, if there is no side effect

**Comment by andersevenrud** [comment]
> As you said, one thing that we can do is to add a session_id in mountpoints, for instanse

Yep, exactly like this. Then monitor when the list goes empty upon logout, at which point it would be safe to unmount.

> And the other option is do not unmounting, if there is no side effect

I would just recommend doing this in your case.

**Comment by mahsashadi** [comment]
Thanks a lot 🙏🙏🙏
