### ISSUE TITLE
Crashing the osjs when uploading a file in dynamic mountpoints that not found

### ISSUE THREAD

**Issue by maryam4s26** [os-js/osjs-server#87]
hi @andersevenrud .

When the server is restarted, the dynamic mountpoints will be deleted from the server.
And the client doesn't notice this change.

If the user clicks on the mountpoints,  gets a 403 error:
![image](https://github.com/os-js/osjs-server/assets/65979871/d5d4acf1-a37d-460d-aa1a-00c996fa8af5)

![image](https://github.com/os-js/osjs-server/assets/65979871/59090cf7-46a8-4e59-a674-05d31dd7dabe)

But if the user uploads a file in the mountpoint client at the same time when mountpoint is not on the server, the server will crash:
![image](https://github.com/os-js/osjs-server/assets/65979871/b16e7ff8-f9e3-46d4-8e5f-f9d2beceb272)

![image](https://github.com/os-js/osjs-server/assets/65979871/a2ab8b8d-9a94-4eae-beec-e3b123a5319d)

**Comment by andersevenrud** [comment]
> When the server is restarted, the dynamic mountpoints will be deleted from the server.
> And the client doesn't notice this change.

Maybe you can recover from this ? Like having the service where you set up these mountpoint store the current state somewhere, and this is loaded when the service starts up ?

**Comment by maryam4s26** [comment]
thank you @andersevenrud. 

I have used [this](https://github.com/os-js/osjs-server/pull/78/files) here as well and it has not crashed
Do you think this solution is wrong?

**Comment by maryam4s26** [comment]
Thank you very much.
I have tested [this](https://github.com/os-js/osjs-server/pull/88) and it solved my problem.

**Comment by andersevenrud** [comment]
Excellent! I really should have seen that edge case when I worked on the previous fix... but at least now I think we have every hole patched up. Thanks for all the reports!

I published a new version with the patch.

Can this issue be closed now ? It was kind of a question and a bug combined, and I'm not sure if my response to the mountpoint stuff answered your needs 😅

**Comment by maryam4s26** [comment]
I am impatiently waiting for your patch version update. @andersevenrud.

**Comment by andersevenrud** [comment]
Oh... I forgot to push my changes to github and only published to npm. Repo has been updated!
